// AUTO-GENERATED by scripts/regen-gallery-data.js — do not edit by hand.
// Run `node scripts/regen-gallery-data.js` to regenerate.

export interface GalleryImage {
  src: string;
  alt: string;
  event: 'argi' | 'max';
  eventName: string;
  eventType: string;
  type: 'image' | 'video';
  width: number;
  height: number;
}

export const galleryImages: GalleryImage[] = [
  {
    "src": "/assets/gallery/20251212_183438_326_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_183730_275_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_191452_880_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_191604_510_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_191733_390_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_191854_890_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_191955_467_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_194203_721_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_194245_879_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_194345_883_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_194852_652_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_194946_367_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_195108_518_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251212_195211_659_1x.jpg",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_133646_250_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_133836_006_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_134212_241_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_134414_608_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_134735_072_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_135127_923_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_135350_566_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_135735_953_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_140000_889_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_140517_498_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_143620_729_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_143907_325_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_144123_557_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_144551_549_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/20251219_150025_041_1x.jpg",
    "alt": "Argi's Party photo booth strip",
    "event": "argi",
    "eventName": "Argi's Party",
    "eventType": "Private Party",
    "type": "image",
    "width": 600,
    "height": 1740
  },
  {
    "src": "/assets/gallery/IMG_1989_20251212_183413_3600.JPG",
    "alt": "SYNC Xmas Party photo booth strip",
    "event": "max",
    "eventName": "SYNC Xmas Party",
    "eventType": "Corporate Event",
    "type": "image",
    "width": 3600,
    "height": 2340
  }
];
