/* eslint-disable */
const fs = require("node:fs");
const path = require("node:path");
const sharp = require("sharp");

const PROJECT_ROOT = path.resolve(__dirname, "..");
const GALLERY_OUT = path.join(PROJECT_ROOT, "public", "assets", "gallery");
const DATA_OUT = path.join(PROJECT_ROOT, "app", "data", "gallery-images.ts");
const JSON_OUT = path.join(PROJECT_ROOT, "public", "assets", "gallery", "manifest.json");

const SOURCES = [
  { dir: path.join(PROJECT_ROOT, "public", "assets", "Argi_Part_1"), event: "argi" },
  { dir: path.join(PROJECT_ROOT, "public", "assets", "Max_Part_2"), event: "max" },
];

const IMAGE_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const VIDEO_EXTS = new Set([".mp4", ".mov", ".webm"]);
const CROP_TOP = 60;

function eventLabel(event) {
  return event === "argi" ? "Argi Party" : "Max Party";
}

async function ensureDir(dir) {
  await fs.promises.mkdir(dir, { recursive: true });
}

async function processImage(srcPath, outPath) {
  const input = sharp(srcPath, { failOn: "none" });
  const meta = await input.metadata();
  const width = meta.width || 0;
  const height = meta.height || 0;

  if (height <= CROP_TOP) {
    await fs.promises.copyFile(srcPath, outPath);
    return { width, height };
  }

  const newHeight = height - CROP_TOP;
  await input
    .extract({ left: 0, top: CROP_TOP, width, height: newHeight })
    .toFile(outPath);

  return { width, height: newHeight };
}

async function getImageDims(filePath) {
  try {
    const meta = await sharp(filePath, { failOn: "none" }).metadata();
    return { width: meta.width || 0, height: meta.height || 0 };
  } catch {
    return { width: 0, height: 0 };
  }
}

async function main() {
  await ensureDir(GALLERY_OUT);
  await ensureDir(path.dirname(DATA_OUT));

  const records = [];
  let imageCount = 0;
  let videoCount = 0;
  let skipCount = 0;

  for (const source of SOURCES) {
    if (!fs.existsSync(source.dir)) {
      console.warn(`Source missing, skipping: ${source.dir}`);
      continue;
    }

    const files = (await fs.promises.readdir(source.dir)).sort();

    for (const file of files) {
      const srcPath = path.join(source.dir, file);
      const stat = await fs.promises.stat(srcPath);
      if (!stat.isFile()) continue;

      const ext = path.extname(file).toLowerCase();
      const outPath = path.join(GALLERY_OUT, file);

      if (IMAGE_EXTS.has(ext)) {
        const { width, height } = await processImage(srcPath, outPath);
        const dims = width && height ? { width, height } : await getImageDims(outPath);
        records.push({
          src: `/assets/gallery/${file}`,
          alt: `${eventLabel(source.event)} photo booth strip`,
          event: source.event,
          type: "image",
          width: dims.width,
          height: dims.height,
        });
        imageCount += 1;
        console.log(`[image] ${source.event} -> ${file} (${dims.width}x${dims.height})`);
      } else if (VIDEO_EXTS.has(ext)) {
        await fs.promises.copyFile(srcPath, outPath);
        records.push({
          src: `/assets/gallery/${file}`,
          alt: `${eventLabel(source.event)} photo booth video`,
          event: source.event,
          type: "video",
          width: 0,
          height: 0,
        });
        videoCount += 1;
        console.log(`[video] ${source.event} -> ${file}`);
      } else {
        skipCount += 1;
        console.log(`[skip ] ${file}`);
      }
    }
  }

  const header = `// AUTO-GENERATED by scripts/crop-strips.js — do not edit by hand.
// Run \`node scripts/crop-strips.js\` to regenerate.

export interface GalleryImage {
  src: string;
  alt: string;
  event: 'argi' | 'max';
  type: 'image' | 'video';
  width: number;
  height: number;
}

export const galleryImages: GalleryImage[] = ${JSON.stringify(records, null, 2)};
`;

  await fs.promises.writeFile(DATA_OUT, header, "utf8");
  await fs.promises.writeFile(JSON_OUT, JSON.stringify(records, null, 2), "utf8");

  console.log("");
  console.log(`Done. images=${imageCount} videos=${videoCount} skipped=${skipCount}`);
  console.log(`Output dir: ${path.relative(PROJECT_ROOT, GALLERY_OUT)}`);
  console.log(`Data file:  ${path.relative(PROJECT_ROOT, DATA_OUT)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
